### ISSUE TITLE
Error: Firebase App named '[DEFAULT]' already exists.

### ISSUE THREAD

**Issue by hmhv1222** [vivtony00/teamform-seed#37]
Error: Firebase App named '[DEFAULT]' already exists.

Need to check whether the firebase database is initialised more than once.

**Comment by bobby414** [comment]
Maybe not the correct answer, but leave only one test.js under file in karma.conf.js can solve the problem
Do not include more than one test.js

**Comment by hmhv1222** [comment]
Only has "js/*.js" included but still nothing works

**Comment by bobby414** [comment]
such as "unit_tests/test.js"

**Comment by hmhv1222** [comment]
Resolved by replacing  'unit_tests/*.js' by 'unit_tests/test_team.js' in karma.conf.js and define controller only once

Case closed.
